apiVersion: apps/v1
kind: Deployment
metadata:
  name: sktoeok3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sktoeok3
  template:
    metadata:
      labels:
        app: sktoeok3
    spec:
      containers:
      - image: okteto.dev/sktoeok3:latest
        name: sktoeok3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "cbe347c0-ef2c-4cdf-97e0-96b848c71251"
        - name: Vless_Path
          value: "/tsoeiwls"
        - name: Vmess_UUID
          value: "f138aabd-5aaf-4893-89a8-d32e2d24cc4f"
        - name: Vmess_Path
          value: "/aoolapwrd"
        - name: Share_Path
          value: "/v2link"
